services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth_db
      - JWT_SECRET=dev-secret-key
      - REFRESH_SECRET=dev-refresh-key
      - API_PORT=3000
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    volumes:
      - .:/app

  mongo:
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
